//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

using System;



/// <summary>
///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
/// </summary>
// Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
// através de uma ferramenta como ResGen ou Visual Studio.
// Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
// com a opção /str, ou recrie o projeto do VS.
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
internal class Orcamento_Formulários_Orc000 {
    
    private static global::System.Resources.ResourceManager resourceMan;
    
    private static global::System.Globalization.CultureInfo resourceCulture;
    
    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
    internal Orcamento_Formulários_Orc000() {
    }
    
    /// <summary>
    ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Resources.ResourceManager ResourceManager {
        get {
            if (object.ReferenceEquals(resourceMan, null)) {
                global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Orcamento.Formulários.Orc000", typeof(Orcamento_Formulários_Orc000).Assembly);
                resourceMan = temp;
            }
            return resourceMan;
        }
    }
    
    /// <summary>
    ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
    ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Globalization.CultureInfo Culture {
        get {
            return resourceCulture;
        }
        set {
            resourceCulture = value;
        }
    }
    
    /// <summary>
    ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap Cancela {
        get {
            object obj = ResourceManager.GetObject("Cancela", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap Check {
        get {
            object obj = ResourceManager.GetObject("Check", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap Consulta {
        get {
            object obj = ResourceManager.GetObject("Consulta", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap DoorOpen {
        get {
            object obj = ResourceManager.GetObject("DoorOpen", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap Editar {
        get {
            object obj = ResourceManager.GetObject("Editar", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap Exclui {
        get {
            object obj = ResourceManager.GetObject("Exclui", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap Fundo {
        get {
            object obj = ResourceManager.GetObject("Fundo", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap Grava {
        get {
            object obj = ResourceManager.GetObject("Grava", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap Importa {
        get {
            object obj = ResourceManager.GetObject("Importa", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap Key {
        get {
            object obj = ResourceManager.GetObject("Key", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap Logo {
        get {
            object obj = ResourceManager.GetObject("Logo", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap Novo {
        get {
            object obj = ResourceManager.GetObject("Novo", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap PHONE02 {
        get {
            object obj = ResourceManager.GetObject("PHONE02", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap PHONE07 {
        get {
            object obj = ResourceManager.GetObject("PHONE07", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap Print {
        get {
            object obj = ResourceManager.GetObject("Print", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap Sair_Image {
        get {
            object obj = ResourceManager.GetObject("Sair.Image", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap Taxas {
        get {
            object obj = ResourceManager.GetObject("Taxas", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
}
